import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import connectDB from './config/db.js';
import authRoutes from './routes/auth.js';
import appointmentRoutes from './routes/appointments.js';
import { crudRouter } from './routes/crudFactory.js';
import patientRoutesModel from './models/Patient.js';
import serviceRoutesModel from './models/Service.js';
import teamRoutesModel from './models/TeamMember.js';
import testimonialRoutesModel from './models/Testimonial.js';
import faqRoutesModel from './models/FAQ.js';
import settingsRoutes from './routes/settings.js';

const app = express();
const allowedOrigins = (process.env.CLIENT_URL || 'http://localhost:5173').split(',').map((item) => item.trim());
app.use(cors({ origin: allowedOrigins, methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'], allowedHeaders: ['Content-Type', 'Authorization'] }));
app.use(express.json({ limit: '50kb' }));
app.get('/', (_req, res) => res.json({ ok: true, service: 'physiocare-backend', message: 'API is live' }));
app.get('/api/health', (_req, res) => res.json({ ok: true, service: 'physiocare-backend' }));
app.use('/api/auth', authRoutes);
app.use('/api/appointments', appointmentRoutes);
app.use('/api/patients', crudRouter(patientRoutesModel, 'Patient'));
app.use('/api/services', crudRouter(serviceRoutesModel, 'Service'));
app.use('/api/team', crudRouter(teamRoutesModel, 'Team member'));
app.use('/api/testimonials', crudRouter(testimonialRoutesModel, 'Testimonial'));
app.use('/api/faqs', crudRouter(faqRoutesModel, 'FAQ'));
app.use('/api/settings', settingsRoutes);
app.use((_req, res) => res.status(404).json({ message: 'Route not found' }));
app.use((error, _req, res, _next) => { console.error(error); res.status(500).json({ message: 'Internal server error' }); });

const port = Number(process.env.PORT || 5000);
connectDB().then(() => app.listen(port, () => console.log(`API running on port ${port}`))).catch((error) => { console.error(error.message); process.exit(1); });
